import { Inter } from "next/font/google";
import "./globals.css";
import Index from "../../pages/index"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Index />
        <h2>ASD</h2>
        {children}
      </body>
    </html>
  );
}



